name: my_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  go_router: ^16.2.1
  equatable: ^2.0.5
  either_dart: ^1.0.0
  shared_preferences: ^2.3.2
  riverpod_annotation: ^3.0.0
  permission_handler: ^11.3.1 # For handling device permissions
  connectivity_plus: ^6.1.0 # Network connectivity detection
  sqflite: ^2.4.1 # Local SQLite database
  path: ^1.9.1 # File path utilities

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.2
  fake_cloud_firestore: ^4.0.0
  riverpod_generator: ^3.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
