// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRWp5N6va7lcVw2Uk2zH0ydG-tl4bNP2k',
    appId: '1:1053164425613:web:a02063e95a957317476dc4',
    messagingSenderId: '1053164425613',
    projectId: 'app-project-25',
    authDomain: 'app-project-25.firebaseapp.com',
    storageBucket: 'app-project-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiq2naEuacBLPb3g0pZ2e3mef-V0XRe6c',
    appId: '1:1053164425613:android:564c2a437134b4af476dc4',
    messagingSenderId: '1053164425613',
    projectId: 'app-project-25',
    storageBucket: 'app-project-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuiLMutKDdedh8SP1HJPtP4iBCygRk790',
    appId: '1:1053164425613:ios:6b857d0e770f2be5476dc4',
    messagingSenderId: '1053164425613',
    projectId: 'app-project-25',
    storageBucket: 'app-project-25.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRWp5N6va7lcVw2Uk2zH0ydG-tl4bNP2k',
    appId: '1:1053164425613:web:6987d9f90fb9f239476dc4',
    messagingSenderId: '1053164425613',
    projectId: 'app-project-25',
    authDomain: 'app-project-25.firebaseapp.com',
    storageBucket: 'app-project-25.firebasestorage.app',
  );
}
