// TEMPLATE FILE - COPY TO firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// ⚠️ SETUP INSTRUCTIONS:
/// 1. Copy this file to 'firebase_options.dart'
/// 2. Replace all 'YOUR_*_HERE' values with actual Firebase config
/// 3. Never commit firebase_options.dart (it's in .gitignore)
/// 4. Get keys from: https://console.cloud.google.com/apis/credentials
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 🔑 REPLACE WITH YOUR ACTUAL FIREBASE CONFIG
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE', // From Google Cloud Console
    appId: 'YOUR_WEB_APP_ID_HERE', // From Firebase Console
    messagingSenderId: 'YOUR_SENDER_ID_HERE', // From Firebase Console
    projectId: 'YOUR_PROJECT_ID_HERE', // Your Firebase project ID
    authDomain: 'YOUR_AUTH_DOMAIN_HERE', // your-project.firebaseapp.com
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // your-project.firebasestorage.app
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY_HERE', // From Google Cloud Console
    appId: 'YOUR_ANDROID_APP_ID_HERE', // From Firebase Console
    messagingSenderId: 'YOUR_SENDER_ID_HERE', // Same as web
    projectId: 'YOUR_PROJECT_ID_HERE', // Same as web
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Same as web
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY_HERE', // From Google Cloud Console
    appId: 'YOUR_IOS_APP_ID_HERE', // From Firebase Console
    messagingSenderId: 'YOUR_SENDER_ID_HERE', // Same as web
    projectId: 'YOUR_PROJECT_ID_HERE', // Same as web
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Same as web
    iosBundleId: 'YOUR_IOS_BUNDLE_ID_HERE', // com.example.yourapp
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY_HERE', // Same as web
    appId: 'YOUR_WEB_APP_ID_HERE', // Same as web
    messagingSenderId: 'YOUR_SENDER_ID_HERE', // Same as web
    projectId: 'YOUR_PROJECT_ID_HERE', // Same as web
    authDomain: 'YOUR_AUTH_DOMAIN_HERE', // Same as web
    storageBucket: 'YOUR_STORAGE_BUCKET_HERE', // Same as web
  );
}